---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: images
spec:
  project: default
  source:
    repoURL: 'https://github.com/alexandreroman/cicd-with-tanzu-gitops.git'
    path: kpack
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
